// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZkZmlpijnLKsGu1-VuadrazBl0IC0thk',
    appId: '1:907454831489:web:8ea8b5ec06f3fd00cea680',
    messagingSenderId: '907454831489',
    projectId: 'shams-al-kananah',
    authDomain: 'shams-al-kananah.firebaseapp.com',
    storageBucket: 'shams-al-kananah.firebasestorage.app',
    measurementId: 'G-V8EBZFPB4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBERZMkgKAWiRTDqIoQoE5J5p3NBD6URyE',
    appId: '1:907454831489:android:bf619717d3c1b233cea680',
    messagingSenderId: '907454831489',
    projectId: 'shams-al-kananah',
    storageBucket: 'shams-al-kananah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQjAUK_M8Uqvh5vsODehnaBFhxnx5bVkU',
    appId: '1:907454831489:ios:9f1edf109e857c5dcea680',
    messagingSenderId: '907454831489',
    projectId: 'shams-al-kananah',
    storageBucket: 'shams-al-kananah.firebasestorage.app',
    iosBundleId: 'com.example.shamsAlKananah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQjAUK_M8Uqvh5vsODehnaBFhxnx5bVkU',
    appId: '1:907454831489:ios:9f1edf109e857c5dcea680',
    messagingSenderId: '907454831489',
    projectId: 'shams-al-kananah',
    storageBucket: 'shams-al-kananah.firebasestorage.app',
    iosBundleId: 'com.example.shamsAlKananah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZkZmlpijnLKsGu1-VuadrazBl0IC0thk',
    appId: '1:907454831489:web:56bffdbe415c46a5cea680',
    messagingSenderId: '907454831489',
    projectId: 'shams-al-kananah',
    authDomain: 'shams-al-kananah.firebaseapp.com',
    storageBucket: 'shams-al-kananah.firebasestorage.app',
    measurementId: 'G-78DR9LV4TW',
  );
}
